### ISSUE TITLE
What's mean hello in that function

### ISSUE THREAD

**Issue by jairoFernandez** [lafvg12/jsonwebcrypto#1]
https://github.com/lafvg12/jsonwebcrypto/blob/a7cb0b46e3b80240649d3f82ddb4be4330515cc2/src/hash.ts#L31

**Comment by lafvg12** [comment]
Thank you for reporting this bug. I appreciate you bringing it to my attention. I have investigated the issue and made the necessary changes to resolve it.

Please update to the latest version and let me know if you encounter any further issues. Your feedback is very valuable in improving the library. 

👨‍💻
